### ISSUE TITLE
remove all docker images on boot

### ISSUE THREAD

**Issue by 030** [030/ansible-pc#5]
```
- cron:
    name: "remove all docker images on boot"
    special_time: reboot
    job: "systemctl stop docker && rm -r /var/lib/docker && systemctl start docker"
```
